#+TITLE: Moang GNU Emacs
#+AUTHOR: Caio V. Fernandes (Moang)
#+DESCRIPTION: Minhas configurações do emacs
#+STARTUP: showeverything
#+OPTIONS: toc:2

* Índice :toc:
- [[#inicialização][Inicialização]]
  - [[#gerenciador-de-pacotes][Gerenciador de pacotes]]
  - [[#carregando-evil-mode][Carregando evil mode]]
  - [[#atalhos-de-teclado][Atalhos de teclado]]
- [[#fontes][Fontes]]
- [[#alterações-da-interface-gráfica][Alterações da interface gráfica]]
  - [[#desabilita-menubar-toolbar-and-scrollbar][Desabilita Menubar, Toolbar and Scrollbar]]
  - [[#mostra-número-das-linhas-e-linhas-truncated][Mostra número das linhas e linhas Truncated]]
- [[#org-mode][ORG mode]]
  - [[#habilitando-o-índice][Habilitando o índice]]
  - [[#trocando-o-asterisco-dos-cabeçalhos][Trocando o asterisco dos cabeçalhos]]
- [[#which-key][Which Key]]

* Inicialização
** Gerenciador de pacotes

#+begin_src emacs-lisp
    (defvar elpaca-installer-version 0.12)
    (defvar elpaca-directory (expand-file-name "elpaca/" user-emacs-directory))
    (defvar elpaca-builds-directory (expand-file-name "builds/" elpaca-directory))
    (defvar elpaca-sources-directory (expand-file-name "sources/" elpaca-directory))
    (defvar elpaca-order '(elpaca :repo "https://github.com/progfolio/elpaca.git"
                                  :ref nil :depth 1 :inherit ignore
                                  :files (:defaults "elpaca-test.el" (:exclude "extensions"))
                                  :build (:not elpaca-activate)))
    (let* ((repo  (expand-file-name "elpaca/" elpaca-sources-directory))
           (build (expand-file-name "elpaca/" elpaca-builds-directory))
           (order (cdr elpaca-order))
           (default-directory repo))
      (add-to-list 'load-path (if (file-exists-p build) build repo))
      (unless (file-exists-p repo)
        (make-directory repo t)
        (when (<= emacs-major-version 28) (require 'subr-x))
        (condition-case-unless-debug err
            (if-let* ((buffer (pop-to-buffer-same-window "*elpaca-bootstrap*"))
                      ((zerop (apply #'call-process `("git" nil ,buffer t "clone"
                                                      ,@(when-let* ((depth (plist-get order :depth)))
                                                          (list (format "--depth=%d" depth) "--no-single-branch"))
                                                      ,(plist-get order :repo) ,repo))))
                      ((zerop (call-process "git" nil buffer t "checkout"
                                            (or (plist-get order :ref) "--"))))
                      (emacs (concat invocation-directory invocation-name))
                      ((zerop (call-process emacs nil buffer nil "-Q" "-L" "." "--batch"
                                            "--eval" "(byte-recompile-directory \".\" 0 'force)")))
                      ((require 'elpaca))
                      ((elpaca-generate-autoloads "elpaca" repo)))
                (progn (message "%s" (buffer-string)) (kill-buffer buffer))
              (error "%s" (with-current-buffer buffer (buffer-string))))
          ((error) (warn "%s" err) (delete-directory repo 'recursive))))
      (unless (require 'elpaca-autoloads nil t)
        (require 'elpaca)
        (elpaca-generate-autoloads "elpaca" repo)
        (let ((load-source-file-function nil)) (load "./elpaca-autoloads"))))
    (add-hook 'after-init-hook #'elpaca-process-queues)
    (elpaca `(,@elpaca-order))

#+end_src
  
** Carregando evil mode

#+begin_src emacs-lisp
            ;; Install use-package support
            (elpaca elpaca-use-package
              ;; Enable use-package :ensure support for Elpaca.
              (elpaca-use-package-mode))

            ;;When installing a package used in the init file itself,
            ;;e.g. a package which adds a use-package key word,
            ;;use the :wait recipe keyword to block until that package is installed/configured.
            ;;For example:
            ;;(use-package general :ensure (:wait t) :demand t)

            ;; Expands to: (elpaca evil (use-package evil :demand t))
            (use-package evil
              :ensure t
              :init
              (setq evil-want-keybinding nil)
              (evil-mode))
            (elpaca evil-collection
              (use-package evil-collection
        	:after evil
      	:config
    	(setq evil-collection-mode-list '(dashboard dired ibuffer))
  	(evil-collection-init)))

            ;;Turns off elpaca-use-package-mode current declaration
            ;;Note this will cause evaluate the declaration immediately. It is not deferred.
            ;;Useful for configuring built-in emacs features.
            (use-package emacs :ensure nil :config (setq ring-bell-function #'ignore))

#+end_src




** Atalhos de teclado

#+begin_src emacs-lisp
(elpaca general
    (use-package general
	:config
	(general-evil-setup)

	;; Set up 'SPC' as the global leader key
	(general-create-definer moang/leader-keys
	:states '(normal insert visuals emacs)
	:keymaps 'override
	:prefix "SPC"
	:global-prefix "M-SPC")

	(moang/leader-keys
	"b" '(:ignore t :wk "buffer")
	"bb" '(switch-to-buffer :wk "Switch buffer")
	"bk" '(kill-this-buffer :wk "Kill this buffer")
	"bn" '(next-buffer :wk "Next buffer")
	"bp" '(previous-buffer :wk "Previous buffer")
	"br" '(revert-buffer :wk "Reload buffer"))

    )
)

#+end_src


* Fontes
Defining the fonts for emacs

#+begin_src emacs-lisp
  (set-face-attribute 'default nil
  	      :font "Jetbrains Mono"
  	      :height 240
  	      :weight 'medium)
  (set-face-attribute 'variable-pitch nil
  	      :font "Ubuntu"
  	      :height 260
  	      :weight 'medium)
  (set-face-attribute 'fixed-pitch nil
  	      :font "Jetbrains Mono"
  	      :height 240
  	      :weight 'medium)

  ;; Makes commented text and keywords italic.
  ;; The font must have an italic face
  (set-face-attribute 'font-lock-comment-face nil
  		      :slant 'italic)
  (set-face-attribute 'font-lock-keyword-face nil
  		      :slant 'italic)

  ;; fix for a bug
  ;; (add-to-list default-frame-alist '(font . "Jetbrains Mono-11"))

  ;; Line spacing
  ;; (setq-default line-spacing 0.12)

#+end_src

* Alterações da interface gráfica
Some changes to the graphical aspects of Emacs.

** Desabilita Menubar, Toolbar and Scrollbar
#+begin_src emacs-lisp
  (menu-bar-mode -1)
  (tool-bar-mode -1)
  (scroll-bar-mode -1)
#+end_src

** Mostra número das linhas e linhas Truncated
#+begin_src emacs-lisp
  (global-display-line-numbers-mode 1)
  (global-visual-line-mode t)
#+end_src

* ORG mode
O ORG mode é uma série de funcionalidades para criar anotações, documentações e afins.

** Habilitando o índice
#+begin_src emacs-lisp
  (elpaca toc-org
  (use-package toc-org
    :commands toc-org-enable
    :init (add-hook 'org-mode-hook 'toc-org-enable))
  )
#+end_src

** Trocando o asterisco dos cabeçalhos
#+begin_src emacs-lisp
  (add-hook 'org-mode-hook 'org-indent-mode)
  (elpaca org-bullets (use-package org-bullets))
  (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))
#+end_src

* Which Key
O Which key é uma ferramenta que indica quais atalhos posso usar durante
a digitação deles. Quando eu aperto a leader key ele aparece no minibuffer.

#+begin_src emacs-lisp
(elpaca which-key
    (use-package which-key
	:init
	(which-key-mode 1)
	:config
	(setq which-key-side-window-location 'bottom
	    which-key-sort-order #'which-key-order-alpha
	    which-key-sort-uppercase-first nil
	    which-key-add-column-padding 1
	    which-key-max-display-columns nil
	    which-key-min-display-lines 6
	    which-key-side-window-slot -10
	    which-key-side-window-max-height 0.25
	    which-key-idle-delay 0.8
	    which-key-max-description-lenght 25
	    which-key-allow-imprecise-window-fit t
	    which-key-separator "  "))
)
  
#+end_src
